### ISSUE TITLE
[Update Request]: Youdao.YoudaoDict -> Youdao.YoudaoTranslate

### ISSUE THREAD

**Issue by vedantmgoyal9** [microsoft/winget-pkgs#119661]
### What type of update are you requesting?

A change to the Package Identifier

### Current Package Identifier

Youdao.YoudaoDict

### Package Version

All versions

### Please describe the changes you would like to see

I found a good way to deal with it (at least for now). Maybe start from September we can change id to youdao.youdaotranslate, because we have gave enough time for users to upgrade.

_Originally posted by @lychichem in https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/1227#issuecomment-1662370344_

* Reference: https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/1227
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/winget-pkgs/pull/119665
- [ ] https://github.com/microsoft/winget-pkgs/pull/119664
- [ ] https://github.com/microsoft/winget-pkgs/pull/119666
- [ ] https://github.com/microsoft/winget-pkgs/pull/119667
- [ ] https://github.com/microsoft/winget-pkgs/pull/119668
- [ ] https://github.com/microsoft/winget-pkgs/pull/119671
- [ ] https://github.com/microsoft/winget-pkgs/pull/119670
- [ ] https://github.com/microsoft/winget-pkgs/pull/119669
- [ ] https://github.com/microsoft/winget-pkgs/pull/119673
- [ ] https://github.com/microsoft/winget-pkgs/pull/119672
- [ ] https://github.com/microsoft/winget-pkgs/pull/119677
- [ ] https://github.com/microsoft/winget-pkgs/pull/119678
- [ ] https://github.com/microsoft/winget-pkgs/pull/119675
- [ ] https://github.com/microsoft/winget-pkgs/pull/119676
- [ ] https://github.com/microsoft/winget-pkgs/pull/119674
- [ ] https://github.com/microsoft/winget-pkgs/pull/119679
- [ ] https://github.com/microsoft/winget-pkgs/pull/119680
- [ ] https://github.com/microsoft/winget-pkgs/pull/119681
- [ ] https://github.com/microsoft/winget-pkgs/pull/119682
- [ ] https://github.com/microsoft/winget-pkgs/pull/119684
- [ ] https://github.com/microsoft/winget-pkgs/pull/119683
- [ ] https://github.com/microsoft/winget-pkgs/pull/119685
- [ ] https://github.com/microsoft/winget-pkgs/pull/119686
- [ ] https://github.com/microsoft/winget-pkgs/pull/119687
- [ ] https://github.com/microsoft/winget-pkgs/pull/119688
- [ ] https://github.com/microsoft/winget-pkgs/pull/119689
- [ ] https://github.com/microsoft/winget-pkgs/pull/119690
```

**Comment by DuckDuckStudio** [comment]
This issue should be closed with completion now.
