### ISSUE TITLE
[New Feature]: #128408 (windows.PCSX2)

### ISSUE THREAD

**Issue by fwadnjar** [microsoft/winget-pkgs#128413]
### Description of the new feature/enhancement

Re: [microsoft/winget-pkgs] New package: windows.PCSX2 version 1.6.0 (PR #127891)

### Proposed technical implementation details (optional)

      MesterPerfect:windows.PCSX2-1.6.0-10b500e4-e5c9-437e-a905-3c8d0cb81243
```[tasklist]
### Tasks
- [x] [New Feature]: #128408 (windows.PCSX2
- [ ] https://github.com/microsoft/winget-pkgs/pull/129588
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/winget-pkgs/issues/128413#issue-2014702580
- [ ] https://github.com/microsoft/winget-pkgs/pull/129588
```

**Comment by stephengillie** [comment]
Hi @fwadnjar,

Could you provide more detail about the feature's purpose and implementation?
