### ISSUE TITLE
[Package Issue]: Xmake-io.Xmake

### ISSUE THREAD

**Issue by Dragon1573** [microsoft/winget-pkgs#138172]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When installing the latest version of _Xmake build utility (x64)_ (aka. `Xmake-io.Xmake`) via _WinGet_, the actual installed version number is `2.8.6+20231226` instead of `2.8.6`. _WinGet_ will regard `v2.8.6` newer than `v2.8.6+20231226`.

It should ...

- either update the `PackageVersion` of `Xmake-io.Xmake`.
- or Add `AppsAndFeaturesEntries` of this package, telling ARP version and manifest version apart.

### Steps to reproduce

1. Try `winget install -e Xmake-io.Xmake`, `winget.exe` should find current latest version `2.8.6`
2. Try `winget update` to see if there's any updates.

### Actual behavior

```text
pwsh> winget list XMake
名称                      ID             版本           可用  源
--------------------------------------------------------------------
Xmake build utility (x64) Xmake-io.Xmake 2.8.6+20231226 2.8.6 winget
```

### Expected behavior

NO newer versions of XMake, as we JUST installed the current latest version.

### Environment

```raw
Windows 程序包管理器(预览) v1.7.3481-preview
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22635.3139
系统体系结构: X64
软件包: Microsoft.DesktopAppInstaller v1.22.3481.0

Winget 目录
-------------------------------------------------------------------------------------------------------------------
日志                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
用户设置               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
可移植链接目录(用户)   %LOCALAPPDATA%\Microsoft\WinGet\Links
可移植链接目录(计算机) C:\Program Files\WinGet\Links
可移植包根目录(用户)   D:\Applications\WinGet\Portable\Users\
可移植包根目录         D:\Applications\WinGet\Portable\Global\
可移植包根目录 (x86)   D:\Applications\WinGet\Portable\Global\
安装程序下载           D:\Download\Aria2

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale

管理员设置                                状态
------------------------------------------------
LocalManifestFiles                        已启用
BypassCertificatePinningForMicrosoftStore 已禁用
InstallerHashOverride                     已禁用
LocalArchiveMalwareScanOverride           已禁用
```

### Screenshots and Logs

```text
pwsh> winget update
名称                      ID             版本           可用  源
--------------------------------------------------------------------
Xmake build utility (x64) Xmake-io.Xmake 2.8.6+20231226 2.8.6 winget
1 升级可用。
1 程序包的版本号无法确定。使用 --include-unknown 查看所有结果。
3 程序包拥有阻止升级的包钉。使用 'winget pin' 命令查看和编辑包钉。使用 --include-pinned 参数可能显示更多结果。

pwsh> sudo winget update --all
名称                      ID             版本           可用  源
--------------------------------------------------------------------
Xmake build utility (x64) Xmake-io.Xmake 2.8.6+20231226 2.8.6 winget
1 升级可用。
1 程序包的版本号无法确定。使用 --include-unknown 查看所有结果。
3 程序包拥有阻止升级的包钉。使用 'winget pin' 命令查看和编辑包钉。使用 --include-pinned 参数可能显示更多结果。

(1/1) 已找到 XMake build utility [Xmake-io.Xmake] 版本 2.8.6
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://github.com/xmake-io/xmake/releases/download/v2.8.6/xmake-v2.8.6.win64.exe
  ██████████████████████████████  3.80 MB / 3.80 MB
已成功验证安装程序哈希
正在启动程序包安装...
已成功安装

1 程序包的版本号无法确定。使用 --include-unknown 查看所有结果。

pwsh> sudo winget update --all
名称                      ID             版本           可用  源
--------------------------------------------------------------------
Xmake build utility (x64) Xmake-io.Xmake 2.8.6+20231226 2.8.6 winget
1 升级可用。
1 程序包的版本号无法确定。使用 --include-unknown 查看所有结果。
3 程序包拥有阻止升级的包钉。使用 'winget pin' 命令查看和编辑包钉。使用 --include-pinned 参数可能显示更多结果。

(1/1) 已找到 XMake build utility [Xmake-io.Xmake] 版本 2.8.6
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://github.com/xmake-io/xmake/releases/download/v2.8.6/xmake-v2.8.6.win64.exe
  ██████████████████████████████  3.80 MB / 3.80 MB
已成功验证安装程序哈希
正在启动程序包安装...
已成功安装

1 程序包的版本号无法确定。使用 --include-unknown 查看所有结果。

pwsh> xmake --version
xmake v2.8.6+HEAD.211710b67, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io

    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor

```

- [WinGet-2024-02-07-00-58-06.084.log](https://github.com/microsoft/winget-pkgs/files/14183777/WinGet-2024-02-07-00-58-06.084.log)
- [WinGet-2024-02-07-00-57-19.062.log](https://github.com/microsoft/winget-pkgs/files/14183778/WinGet-2024-02-07-00-57-19.062.log)
- [WinGet-2024-02-07-00-57-39.192.log](https://github.com/microsoft/winget-pkgs/files/14183779/WinGet-2024-02-07-00-57-39.192.log)
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/winget-pkgs/pull/138180
```
