### ISSUE TITLE
[Update Request]: KNIME

### ISSUE THREAD

**Issue by Akaizoku** [microsoft/winget-pkgs#168566]
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

KNIMEAG.KNIMEAnalyticsPlatform

### Package Version

5.3.1

### Please describe the changes you would like to see

Knime has published four new versions since 5.2.3.

P.S. Since the installers are the exact same for both admin and user installation, could we simplify the manifest to only include one URL?

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/winget-pkgs/pull/168569
- [ ] https://github.com/microsoft/winget-pkgs/pull/168568
- [ ] https://github.com/microsoft/winget-pkgs/pull/168565
- [ ] https://github.com/microsoft/winget-pkgs/pull/168570
```

**Comment by Dragon1573** [comment]
Already resolved and should be closed as "completed".

**Comment by stephengillie** [comment]
> Already resolved and should be closed as "completed".
