### ISSUE TITLE
[Update Request]: Microsoft.Dotnet.* (update CDN urls)

### ISSUE THREAD

**Issue by a-mnich** [microsoft/winget-pkgs#202037]
### What type of update are you requesting?

Something else not listed

### Current Package Identifier

Microsoft.Dotnet.*

### Package Version

multiple

### Please describe the changes you would like to see

As announced in https://github.com/dotnet/core/issues/9671 the hoster of the CDNs `https://dotnetcli.azureedge.net/` and `https://dotnetbuilds.azureedge.net/` will soon seize operations due to bankrupcy.  
It is recommended that users switch to the new CDN domains as quickly as possible.   
While a majority of the newest versions `Microsoft.Dotnet.*`packages has already been switched to the new  CDN by @mthalman  (e.g. in PR https://github.com/microsoft/winget-pkgs/pull/200316) there are still a lot of packages with the old domains remaining.  

A [GitHub Search](https://github.com/search?q=repo%3Amicrosoft%2Fwinget-pkgs%20https%3A%2F%2Fdotnetcli.azureedge.net&type=code) for `https://dotnetcli.azureedge.net/`  gets results in 620 files within this repository.

**Action steps:**
Open PRs to switch the installer domain from `https://dotnetcli.azureedge.net/` to `builds.dotnet.microsoft.com`  for all packages found in the GitHub search.

**Comment by flo7000** [comment]
hello,
i'd like to do that but i have a question:
i should do a PR for each package, right?

and starting at which point of the path do i count it as a whole package? at "SDK" in that example?
/manifests/m/Microsoft/DotNet/SDK/6/6.0.122/Microsoft.DotNet.SDK.6.installer.yaml

**Comment by Dragon1573** [comment]
> I should do a PR for each package, right?

I think you may need to create pull requests for each versions of these packages.

"Sparse checkout" feature is enabled on my local clone. Sparse checkout the directory `/manifests/m/Microsoft/DotNet` with `--no-cone` mode and try following command. You'll have to create such that LARGE amount of pull requests ...

```text
22:06:14 D:\...\winget-pkgs  [master ≡] 1ms pwsh> C:\Applications\Git\Git\usr\bin\find.exe ./manifests/m/Microsoft/DotNet -type f -name '*installer.yaml' | C:\Applications\Git\Git\usr\bin\wc.exe -l
585
```

**Comment by flo7000** [comment]
okay, i understand, thank you!

so i can be sure that all the paths exist at the new domain? not that i'd have to test that too :D

**Comment by Dragon1573** [comment]
> So I can be sure that all the paths exist at the new domain? not that I'd have to test that too :D

Neither can't I. I've just tested one URL and it's valid. There might need a script for automatically checking these URLs.

**Comment by flo7000** [comment]
Checklist for all DotNet "Subpackages"

- [ ] SDK -> 189 files
  - [ ] SDK 3_1  -> 8 files
  - [ ] SDK 5 -> 2 files
  - [ ] SDK 6 -> 77 files
  - [ ] SDK 7 -> 50 files
  - [ ] SDK 8 -> 26 files
  - [ ] SDK 9 -> 1 file
  - [ ] SDK Preview -> 25 files

- [ ] Runtime -> 93 files
  - [ ] Runtime 3_1  -> 8 files
  - [ ] Runtime 5 -> 1 file
  - [ ] Runtime 6 -> 30 files
  - [ ] Runtime 7 -> 20 files
  - [ ] Runtime 8 -> 10 files
  - [ ] Runtime 9 -> Nothing left
  - [ ] Runtime Preview -> 24 files

- [ ] HostingBundle -> 92 files
  - [ ] HostingBundle 3_1  -> 8 files
  - [ ] HostingBundle 5 -> 1 file
  - [ ] HostingBundle 6 -> 29 files
  - [ ] HostingBundle 7 -> 20 files
  - [ ] HostingBundle 8 -> 10 files
  - [ ] HostingBundle 9 -> Nothing left
  - [ ] HostingBundle Preview -> 24 files

- [ ] DesktopRuntime -> 93 files
  - [ ] DesktopRuntime 3_1  -> 8 files
  - [ ] DesktopRuntime 5 -> 1 file
  - [ ] DesktopRuntime 6 -> 30 files
  - [ ] DesktopRuntime 7 -> 20 files
  - [ ] DesktopRuntime 8 -> 10 files
  - [ ] DesktopRuntime 9 -> Nothing left
  - [ ] DesktopRuntime Preview -> 24 files

- [ ] AspNetCore -> 92 files
  - [ ] DesktopRuntime 3_1  -> 8 files
  - [ ] DesktopRuntime 5 -> 1 file
  - [ ] DesktopRuntime 6 -> 29 files
  - [ ] DesktopRuntime 7 -> 20 files
  - [ ] DesktopRuntime 8 -> 10 files
  - [ ] DesktopRuntime 9 -> Nothing left
  - [ ] AspNetCore Preview -> 24 files

I've started with SDK 3_1 as a test (because I can be sure that nobody else is editing that manifest) but I'll do all 8/9/Preview Manifests first :)

**Comment by flo7000** [comment]
@a-mnich , is this due January 15 2025 ?

https://learn.microsoft.com/en-us/azure/cdn/edgio-retirement-faq

this FAQ says the following:

> Edgio has informed us that their services will remain operational until at least January 15, 2025. However, we can't guarantee that Edgio won't unexpectedly cease operations before this date due to circumstances beyond our control.

**Comment by a-mnich** [comment]
@flo7000 I don't have any additional insight. Therefore I would stick to the information from the FAQ.

**Comment by flo7000** [comment]
@a-mnich what packages are you gonna update? not that we do something double 

and how do you update them all with a bot? :O

**Comment by a-mnich** [comment]
@flo7000  
I think it's easiest to go package wise, so I'm gonna do all `Microsoft.DotNet.AspNetCore` versions now. (I'm working bottom to top in your list :D)   
If no problems arise in the validation pipeline, I will open subsequent PRs after the first batch is merged.  
  
Since you worked on it first I don't want to “take anything away” from you and we always appreciate new contributors for maintaining the packages. :)  I's quite easy for me to create bulk package upgrades like this as I've implemented an automation for such jobs.

I will open up the PRs for:
- `Microsoft.DotNet.AspNetCore`
- `Microsoft.DotNet.DesktopRuntime`
- `Microsoft.DotNet.HostingRuntime`
- `Microsoft.DotNet.Runtime`

Then there's `Microsoft.DotNet.SDK` left for you to do. Just leave a quick message in this thread if I should take over anything. :)

**Comment by flo7000** [comment]
https://github.com/microsoft/winget-pkgs/pull/202218#pullrequestreview-2523540153 

I'll update them to 1.9 (I tried but didn't know that I needed to update all 3 files)!

> Since you worked on it first I don't want to “take anything away” from you and we always appreciate new contributors for maintaining the packages. :) I's quite easy for me to create bulk package upgrades like this as I've implemented an automation for such jobs.

okay, thank you! 

do you have maybe a documentation about the automation somewhere? i'd be interested to learn more about that :)

**Comment by flo7000** [comment]
@a-mnich - done (the validation is still running but already moderator approved)

do you know if the following packages are also affected? because i think the links should be changed there too? 

Microsoft.AzureDataStudio.* 
Microsoft.Azure.*
Microsoft.EdgeDriver.*  

the microsoft manifests are 366 of the 378 results for the search `repo:microsoft/winget-pkgs azureedge.net ` / 
 ` repo:microsoft/winget-pkgs path:manifests/m/Microsoft azureedge.net `

**Comment by o-l-a-v** [comment]
From reading this GitHub issue: <https://github.com/dotnet/core/issues/9671>

It seems that all `*.azureedge.net` subdomains can stop working. So not only Microsoft software.

> It is possible that .azureedge.net domains will have downtime or become permanently unavailable.

* Search for `azureedge.net`:<https://github.com/search?q=repo%3Amicrosoft%2Fwinget-pkgs%20azureedge.net&type=code>

**Comment by a-mnich** [comment]
According to the [migration FAQ](https://learn.microsoft.com/en-us/azure/cdn/edgio-retirement-faq#can-i-retain-my-existing-azureedgenet-domain-when-i-move-to-azure-front-door), an automatic migration to Azure Front Door as new CDN will be performed on January 7 for all customers that haven't migrated yet.  
The domains should continue to work short term , but all `*.azureedge.net` ultimatively need to be phased out.
> Relying on domains like *.azureedge.net and *.azurefd.net isn't recommended as it poses availability risks. [...]  It's advisable to adopt a custom domain as soon as possible.
  
The documentation states that, moving forward, custom domains should be used. Each package publisher will need to decide on a new domain themselves.  
Therefore, most likely there won't be any general migration strategy to migrate all packages at once to one specific new domain.  
  
A quick check of the websites for some affected packages shows that the download links for the current versions of 
 `LINQPad.LINQPad.8`, `Microsoft.Azure.AZCopy.10` and  `Microsoft.EdgeDriver` still point to  `azureedge.net` domains. I suspect it will take some time for all publishers to adopt this change.

**Comment by mthalman** [comment]
Looks like everything is updated. Thanks! This can be closed now.
