### ISSUE TITLE
Package Request: Microsoft ToDo

### ISSUE THREAD

**Issue by y-sera** [microsoft/winget-pkgs#21625]
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**:            Microsoft Corporation

**Publisher Url**:       https://www.microsoft.com/p/microsoft-to-do-lists-tasks-reminders/9nblggh5r558

**Package Name**:   

**Package Url**:    

**Description**:   Got something on your mind? Get Microsoft To Do. Whether you want to increase your productivity, decrease your stress levels, or just free up some mental space, Microsoft To Do makes it easy to plan your day and manage your life.

**Package Version**:

**Installer URL**:

## For new versions:

**Current Package Identifier**:

## Comment
I find the commit  "Add Microsoft To Do 2.19.31501.0 \#1807", but I can't find it in winget search.  
Because I'm beginner and I can't use English well, if this request is stupid I'm sorry.

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-cli/issues/117

**Comment by y-sera** [comment]
Thank you. I try read this link.

**Comment by Trenly** [comment]
@ItzLevvie I think this can be closed when you submit your next PR?
