### ISSUE TITLE
[Package Request]: EaseUS Todo Backup

### ISSUE THREAD

**Issue by OfficialEsco** [microsoft/winget-pkgs#67798]
### Package Requested

- [X] I would like someone else to build the manifest.
- [X] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: EaseUS
Software Url: https://www.easeus.com/backup-software/personal.html
Package Name: EaseUS Todo Backup Free
Package Version: 2022.2
Package Identifier: EaseUS.TodoBackup

Oke so we all know how this goes
https://down.easeus.com/product/tb_free?ref=/backup-software/tb-free.html / https://down.easeus.com/product/tb_free is the Online installer that does not work, however the installer downloads the software to the current folder

https://download.easeus.com/free/tb_free.exe downloads 13.5

I've had no luck with `https://download.easeus.com/free/tb_free_B**.exe` or `https://download.easeus.com/free/tb_freeB**.exe`

Happy hunting for the real url =)

Ref previous issues: https://github.com/microsoft/winget-pkgs/issues/34766

-----

Trenly found https://www.easeus.com/download-offline.html which resolves all our problems

**Comment by Trenly** [comment]
@OfficialEsco - Should we keep this open still?

**Comment by OfficialEsco** [comment]
Weeeell, we don't have 2022.2 yet, but since the url at https://www.easeus.com/download-offline.html just shows the one we have i guess its okay to close?

**Comment by Yousha** [comment]
Resolved by #67800 ?
