### ISSUE TITLE
[PSA] Progress on Support for v1.4 Manifests and .zip Installers

### ISSUE THREAD

**Issue by Trenly** [microsoft/winget-pkgs#87300]
As Winget v1.4 comes closer to release, so does Manifest Specification 1.4. Along with this will be support for .zip based manifests, changes to the documentation, YamlCreate support, and more.  As has been noted by @denelon - 
> We will not begin accepting .zip based manifests until >50% of users have the Generally Available (GA) 1.4 client. We will be flighting the 1.4 Release Candidate build for about a month via Windows Insider Release Preview ahead of GA. They can certainly be submitted ahead of time, and we'll mark them as blocked by .zip until we're ready to start validating.

Below is a snapshot of some of the items required for the 1.4 manifest release, and the progress against them. This is not a comprehensive list, but has been put together for community awareness.

- [x] WinGet version 1.4 released to General Availability (GA)
- [x] Manifest specification 1.4 added to docs in winget-pkgs (#87347)
- [x] PR template updated to reflect manifest 1.4 (#87347)
- [x] Other documentation updated to reference 1.4 at winget-pkgs (#87347)
- [x] Other documentation updated at winget-cli (microsoft/winget-cli#2659)
- [x] WinGet version 1.4 adopted by >50% of users 
- [x] Pipelines updated to use WinGet v1.4 client for PR validation
- [x] Pipelines updated to accept manifest v1.4
- [x] WinGetCreate v1.2 (support for manifest v1.4) released
- [x] YamlCreate updated to support manifest v1.4 - Done! YamlCreate supports v1.4 manifests by enabling developer options and setting the manifest version override in the [script settings](https://github.com/microsoft/winget-pkgs/blob/master/doc/tools/YamlCreate.md#yamlcreate-settings)
- [x] YamlCreate updated to use manifest v1.4 by default (#87349)
- [ ] Documentation on learn.microsoft.com updated to reflect v1.4 changes

**Comment by denelon** [comment]
Hey everybody we jumped the gun a little bit and updated the bot and the PR template to reference the 1.4 schema. We'll add "Blocking-Issue" and ".zip" to those PRs, and as soon as 1.4 validation goes live, we will re-run them.

**Comment by denelon** [comment]
We started the roll out for 1.4 validation and ran into a couple of endpoints that weren't updated. We're deploying the changes now and we will try again after the nodes have been updated.
